[package]
name = "piccolo"
version = "0.3.4"
edition = "2024"

[dependencies]
# Color
prisma = { version = "0.1" }
angular-units = { version = "0.2" }
oklab = { version = "1.1" }

# Utils
strum = { version = "0.28", features = ["derive"] }
struct_iterable = { version = "0.1" }

gtk = { version = "0.11", package = "gtk4", features = ["gnome_50"] }
adw = { package = "libadwaita", version = "0.9", features = ["v1_9"] }
ashpd = { version = "0.13", default-features = false, features = [
    "gtk4",
    "async-io",
    "screenshot",
] }
gettext-rs = { version = "0.8", features = ["gettext-system"] }
