name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    container:
      image: rust:slim
    steps:
      - uses: actions/checkout@v4

      - name: Add rustfmt
        run: rustup component add rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  cargo-clippy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps: 
      - uses: actions/checkout@v4

      - name: Runtime information
        run: |
          # Report the installed versions of the runtime
          flatpak info org.gnome.Platform
          flatpak info org.gnome.Sdk

      - name: Prepare builder
        run: |
          flatpak install -y flathub org.freedesktop.Sdk.Extension.rust-stable/x86_64/25.08
          flatpak-builder --user --disable-rofiles-fuse --force-clean --keep-build-dirs --stop-at=piccolo flatpak_app dist/linux/flatpak/art.fatdawlf.Piccolo.Devel.json
          flatpak build-finish --socket=x11 --share=network flatpak_app

      - name: Run Clippy
        run: |
          xvfb-run -a -s "-screen 0 1024x768x24" \
            flatpak-builder --user --disable-rofiles-fuse --build-shell=piccolo flatpak_app dist/linux/flatpak/art.fatdawlf.Piccolo.Devel.json <<END \
              cargo clippy -- -D warnings \
            END


  flatpak-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: art.fatdawlf.Piccolo.flatpak
          manifest-path: dist/linux/flatpak/art.fatdawlf.Piccolo.Devel.json
          branch: main
